name: AutoLayoutExamples
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "11.0"
targets:
  AutoLayoutExamples:
    type: application
    platform: iOS
    sources: [AutoLayoutExamples]
    settings:
      base:
        SWIFT_VERSION: 5